# @file update-release-draft.yml
#
# Creates and continiously updates a release draft based on the PRs in the repository.
#
# This workflow takes advantage of the labels used in the project to automatically categorize the types of
# changes in a given release. In addition, the semantic version of the code is constantly maintianed using
# typical semantic versioning rules.
#
# Requirements:
# - The calling repo must have a file named `.github/release-draft-config.yml` that contains the configuration
#   for the release drafter action.
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##
name: Update Release Draft

on:
  workflow_call:

jobs:
  draft:
    name: Update Release Draft

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Build a Release Draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-draft-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
